export { default as Login } from './Login';
export { default as Signup } from './Signup';
export { default as Deal } from './Deal';
export { default as Events } from './Events';
export { default as LeadAngel } from './LeadAngel';
export { default as Home } from './Home';
export { default as MyPage } from './MyPage';
export { default as Portfolio } from './Portfolio';
export { default as Settings } from './Settings';
